//@Host = https://nanofinancetracker-webapi-fragrant-surf-6779.fly.dev
@Host = https://localhost:7268

@Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Imp0dHgtRDlPWWFmdi14ZlpjaXNCcCJ9.eyJpc3MiOiJodHRwczovL2Rldi04Y3ZxNGJqbzAydnltOHpxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExMTY4NDk5MTkwNjc2MzAzNjEzNiIsImF1ZCI6WyJuYW5vLWZpbmFuY2UtdHJhY2tlciIsImh0dHBzOi8vZGV2LThjdnE0YmpvMDJ2eW04enEudXMuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTczODM4NTM5MSwiZXhwIjoxNzM4NDcxNzkxLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIiwiYXpwIjoiT3FqZ2hQc0NQZlIxVEJ3cXZoa3NRWGE1d0ZXOTZKaWIifQ.V3evODtgXKb1VY8_DXNG1xhFxZDd9aiZjTUD7kmcMShJ7z-gHcKqBudz8TazsZ1H6zpbko__yrRO3_wfBkTJMTiOYYkmYqDyQmSabYYvbDABMtRrd0jfcorus1YJRiMxSqvyavVxVWXSCvQFG0-lnHk57OAPjGqGEsH2jExESihwilMzJoArCKqpYKCx5HHxtu7gwRaPLkSjVfciow-xTrICUo73BqH2_L5INXJ3G7MhHikkotdyRHrLfb6-NXrXLPBX9OIdgDkiCc9Y7tGjkJ84KMMj6ErGJ-vniR6FxttWk7e46CDGvkZoGfTtOBGlKLuntyXm7YK0CJjlWAJkSA
@account = bdo
GET {{Host}}/weatherforecast/
Accept: application/json

######
GET {{Host}}/api/FinanceMonth/{{account}}/2024/8
Authorization: Bearer {{Token}}


######
GET {{Host}}/api/FinanceMonth/{{account}}/2024/8/transactions
Authorization: Bearer {{Token}}

###
POST {{Host}}/api/FinanceMonth/{{account}}/2024/8/incomes
content-type: application/json
Authorization: Bearer {{Token}}

{
  "amount": 100,
  "description": "string",
  "category": "string",
  "transactionDate": "2024-08-24T14:28:04.256Z"
}

###
POST https://localhost:7268/api/FinanceMonth/{{account}}/2024/8/expenses
content-type: application/json
Authorization: Bearer {{Token}}

{
  "amount": 100,
  "description": "string",
  "category": "string",
  "transactionDate": "2024-08-24T14:28:04.256Z"
}

###
GET {{Host}}/api/Accounts
content-type: application/json
Authorization: Bearer {{Token}}
