@Host = http://localhost:5249

@Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Imp0dHgtRDlPWWFmdi14ZlpjaXNCcCJ9.eyJpc3MiOiJodHRwczovL2Rldi04Y3ZxNGJqbzAydnltOHpxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NWU4MmViYmU3MDdjYmMzZWVhNWQ0ODQiLCJhdWQiOlsibmFuby1maW5hbmNlLXRyYWNrZXIiLCJodHRwczovL2Rldi04Y3ZxNGJqbzAydnltOHpxLnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3MjUyOTIxNDQsImV4cCI6MTcyNTM3ODU0NCwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSIsImF6cCI6Ilg3SVF0aFNpakJMWHh0b09SUFFTbjFCOUxtaU1sUDRJIn0.IWBxW9qzzFEtd8Q77YWb8hkyEKlPXhT2cWZYkxWYDFjMJBb4ivEHFXwyD9CNpZvR85Tg5Kgz7YmAwrGKWiSwvxw0s4O1rBuL9LrIOjh2Fe4GecBOacIyDLFY85GPSQWZfYnL0NjWGzfkeC7GT1ugG7BoqdjsrSS9vJQuSfhCNNUSn0ci0n7ESNPfWO1EATPVCJvZtLurUldg6acwiawge3VDJcNM3kKhYQc7XID7panxGldjU3UNKGE4QL-34TgcjtW4LYM_ohtq8yyuaxmutc3zZ--99robKdl0tKBcK0LSO4qYHHrrMXED_5-P9ZTO3iAuGnCgpKYQ6QFG64rnSA

GET {{Host}}/weatherforecast/
Accept: application/json

######
GET https://localhost:7268/api/FinanceMonth/2024/8
Authorization: Bearer {{Token}}

###
POST https://localhost:7268/api/FinanceMonth/2024/8/incomes
content-type: application/json
Authorization: Bearer {{Token}}

{
  "amount": 100,
  "description": "string",
  "category": "string",
  "transactionDate": "2024-08-24T14:28:04.256Z"
}

###
POST https://localhost:7268/api/FinanceMonth/2024/8/expenses
content-type: application/json
Authorization: Bearer {{Token}}

{
  "amount": 100,
  "description": "string",
  "category": "string",
  "transactionDate": "2024-08-24T14:28:04.256Z"
}

### Login

