@Host = https://localhost:7268

@Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Imp0dHgtRDlPWWFmdi14ZlpjaXNCcCJ9.eyJpc3MiOiJodHRwczovL2Rldi04Y3ZxNGJqbzAydnltOHpxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJqTEdzUzBCUUFhNno5bXVmdFM5M3U3VVhwbUVNZzJ1TUBjbGllbnRzIiwiYXVkIjoibmFuby1maW5hbmNlLXRyYWNrZXIiLCJpYXQiOjE3MjcwMDcwNTcsImV4cCI6MTcyNzA5MzQ1NywiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoiakxHc1MwQlFBYTZ6OW11ZnRTOTN1N1VYcG1FTWcydU0ifQ.IXXeZ6OCOPuW_peE0c4ub8m0wCK_uLutngYGILOiqBuoTAhWyI1lqgHdnCDnYZxSt8CekGdCxBSBC4slDkJNJylAweS4UlBs13Qqfz2954mPNqG--JHilDflbNdUJHYr4cj2cLwC8BcmLGNEnQh0Qt8co0j5ibtW7YqMc4aC0Atf0eBzGsa6tRRf43uaOXzrzlHp8VqVAJtLl_I64jV7FSAGbZrOkSP2cD2aLG9_hAMZEqLFaELVvj3Jqu0JhD1S0vLKqgm52wwNd-Cqt-FeyqHex08yvSBnleYSYKhXHrPmoqKDGmWvj_TBBNBNiKLHPfdQxEC1ynR98el_RjWqaQ
@account = bdo
GET {{Host}}/weatherforecast/
Accept: application/json

######
GET {{Host}}/api/FinanceMonth/{{account}}/2024/8
Authorization: Bearer {{Token}}


######
GET {{Host}}/api/FinanceMonth/{{account}}/2024/8/transactions
Authorization: Bearer {{Token}}

###
POST {{Host}}/api/FinanceMonth/{{account}}/2024/8/incomes
content-type: application/json
Authorization: Bearer {{Token}}

{
  "amount": 100,
  "description": "string",
  "category": "string",
  "transactionDate": "2024-08-24T14:28:04.256Z"
}

###
POST https://localhost:7268/api/FinanceMonth/{{account}}/2024/8/expenses
content-type: application/json
Authorization: Bearer {{Token}}

{
  "amount": 100,
  "description": "string",
  "category": "string",
  "transactionDate": "2024-08-24T14:28:04.256Z"
}

### Login

